remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Associaci贸 Cave Cavet
author: 
description: Web de l'Associaci贸 per la difusi贸 de informaci贸
show_downloads: false
google_analytics: G-387JH7XMYM
